parameters:
    mailer.imap_debug_folder: /tmp/imap_debug

services:
    mailer.password_handler:
        class: Mailer\MailBundle\Service\PasswordHandlerService
        arguments:
            - %mailer.secret%
    mailer.imap:
        class: Mailer\MailBundle\Service\ImapService
        arguments:
            - %mailer.imap_debug_folder%
            - @mailer.password_handler
