parameters:
    mailer.imap_debug_folder: /tmp/imap_debug

services:
    mailer.password_handler:
        class: Mailer\MailBundle\Service\PasswordHandlerService
        arguments:
            - %mailer.secret%
    mailer.imap:
        class: Mailer\MailBundle\Service\ImapService
        arguments:
            - @mailer.password_handler
    mailer.app.twig_extension:
        class: Mailer\AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }