services:
    register_user_command_handler:
        class: Mailer\MailBundle\CommandHelper\AddAccountCommandHelper
        arguments:
            - @doctrine
        tags:
            - { name: command_handler, handles: Mailer\MailBundle\Command\AddAccountCommand }