index:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: unified_inbox
        permanent: true

unified_inbox:
    path: /inbox
    defaults: { _controller: MailerAppBundle:App:unifiedInbox }

settings:
    path: /settings
    defaults: { _controller: MailerAppBundle:App:settings }

accounts:
    resource: @MailerAppBundle/Resources/config/Account/routing.yml
    prefix: /account
