Mailer\DataBundle\Entity\Account:
    properties:
        email:
            - Email: ~
        server:
            - NotBlank: ~
        username:
            - NotBlank: ~
        password:
            - NotBlank: ~
        creationDate:
            - DateTime: ~
