Mailer\DataBundle\Entity\Account:
    properties:
        title:
            - NotBlank: ~
        server:
            - NotBlank: ~
        username:
            - NotBlank: ~
        password:
            - NotBlank: ~
        creationDate:
            - DateTime: ~
